### ISSUE TITLE
Data cleaning pipeline

### ISSUE THREAD

**Issue by jonathancstroud** [MichiganDataScienceTeam/flint-water#1]
We need a shared pipeline for cleaning and merging different sources of data. Specifically, I mean:
- Joining the parcel data with the sentinel/residential data
- Parsing addresses
- Recovering lat/lon coordinates from addresses
- etc.

**Comment by the-alex** [comment]
Honestly, this should be a data drive / hack day ticket item. Investing in organization now will be critical for on-boarding new members and reproducing our results. It's super boring and super dry but **_REALLY IMPORTANT**_.
